# Generated by Django 4.2.17 on 2025-01-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='button_type',
            field=models.CharField(blank=True, choices=[('demo', 'Demo'), ('video', 'Video')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, help_text='URL for Demo button', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g., dQw4w9WgXcQ from https://www.youtube.com/watch?v=dQw4w9WgXcQ)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
